/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_jiangyouxin_vnotepad_SyncTask */

#ifndef _Included_net_jiangyouxin_vnotepad_SyncTask
#define _Included_net_jiangyouxin_vnotepad_SyncTask
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_jiangyouxin_vnotepad_SyncTask
 * Method:    xdl_merge
 * Signature: ([B[B[BIIIIILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_jiangyouxin_vnotepad_SyncTask_xdl_1merge
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jint, jint, jint, jint, jint, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
